#learn-ease-fyp\backend\services\subject_service.py
from motor.motor_asyncio import AsyncIOMotorDatabase
from typing import List, Optional
from bson import ObjectId
from datetime import datetime

from models.subject_schemas import SubjectCreate, SubjectInDBBase, SubjectUpdate
from models.user_schemas import PyObjectId # Assuming PyObjectId is correctly defined and used

# Name of the MongoDB collection for subjects
SUBJECTS_COLLECTION = "subjects"
BOOKS_COLLECTION = "books"

async def create_subject(
    db: AsyncIOMotorDatabase, 
    subject_in: SubjectCreate, 
    user_id: PyObjectId
) -> SubjectInDBBase:
    """
    Creates a new subject for a user.
    Checks for duplicate subject names for the same user (case-insensitive).
    """
    # Check if subject with the same name already exists for this user (case-insensitive)
    existing_subject = await db[SUBJECTS_COLLECTION].find_one(
        {"user_id": user_id, "name": {"$regex": f"^{subject_in.name}$", "$options": "i"}}
    )
    if existing_subject:
        raise ValueError(f"Subject with name '{subject_in.name}' already exists for this user.")

    subject_doc = SubjectInDBBase(
        name=subject_in.name,
        user_id=user_id,
        created_at=datetime.utcnow() 
        # id will be generated by default_factory if not provided, or by MongoDB if not in Pydantic model upon insert
    )
    
    # Use mode='python' to preserve ObjectIds
    subject_dict_for_db = subject_doc.model_dump(by_alias=True, exclude_none=True, mode='python')
    
    # Manually remove 'id' if it's None to let MongoDB generate it,
    # or ensure your Pydantic model's default_factory for id works as expected.
    if subject_dict_for_db.get("_id") is None:
        subject_dict_for_db.pop("_id", None)
    
    # Ensure user_id is stored as ObjectId
    if "user_id" in subject_dict_for_db and isinstance(subject_dict_for_db["user_id"], str):
        subject_dict_for_db["user_id"] = ObjectId(subject_dict_for_db["user_id"])

    result = await db[SUBJECTS_COLLECTION].insert_one(subject_dict_for_db)
    
    created_subject_doc = await db[SUBJECTS_COLLECTION].find_one({"_id": result.inserted_id})
    if not created_subject_doc:
        # This would be unusual if insert_one succeeded
        raise Exception("Failed to retrieve subject after creation.")
        
    return SubjectInDBBase(**created_subject_doc)

async def get_subjects_by_user(
    db: AsyncIOMotorDatabase, 
    user_id: PyObjectId
) -> List[SubjectInDBBase]:
    """
    Retrieves all subjects for a specific user, sorted by creation date.
    """
    subjects_cursor = db[SUBJECTS_COLLECTION].find({"user_id": user_id}).sort("created_at", 1) # Sort by oldest first, or -1 for newest
    db_subjects = await subjects_cursor.to_list(length=None) # Fetch all
    return [SubjectInDBBase(**subj_doc) for subj_doc in db_subjects]

async def get_subject_by_id_for_user(
    db: AsyncIOMotorDatabase, 
    subject_id_str: str, 
    user_id: PyObjectId
) -> Optional[SubjectInDBBase]:
    """
    Retrieves a specific subject by its ID, ensuring it belongs to the user.
    """
    try:
        subject_oid = PyObjectId(subject_id_str) # Validate and convert string ID
    except Exception: # Catch errors from PyObjectId validation (e.g., invalid format)
        return None 
        
    subject_doc = await db[SUBJECTS_COLLECTION].find_one({"_id": subject_oid, "user_id": user_id})
    if subject_doc:
        return SubjectInDBBase(**subject_doc)
    return None

async def update_subject_name(
    db: AsyncIOMotorDatabase, 
    subject_id_str: str, 
    subject_update: SubjectUpdate, 
    user_id: PyObjectId
) -> Optional[SubjectInDBBase]:
    """
    Updates the name of a subject.
    Ensures the new name isn't a duplicate for the same user (excluding the current subject being updated).
    """
    subject_to_update = await get_subject_by_id_for_user(db, subject_id_str, user_id)
    if not subject_to_update:
        return None # Subject not found or doesn't belong to user

    # Check if another subject with the new name already exists for this user
    existing_subject_with_new_name = await db[SUBJECTS_COLLECTION].find_one(
        {
            "user_id": user_id, 
            "name": {"$regex": f"^{subject_update.name}$", "$options": "i"},
            "_id": {"$ne": subject_to_update.id} # Exclude the current subject itself
        }
    )
    if existing_subject_with_new_name:
        raise ValueError(f"Another subject with name '{subject_update.name}' already exists for this user.")

    update_data = {"$set": {"name": subject_update.name}}
    # Optional: add updated_at field: 
    # update_data["$set"]["updated_at"] = datetime.utcnow() 

    await db[SUBJECTS_COLLECTION].update_one(
        {"_id": subject_to_update.id, "user_id": user_id}, 
        update_data
    )
    
    updated_subject_doc = await db[SUBJECTS_COLLECTION].find_one({"_id": subject_to_update.id})
    if updated_subject_doc:
        return SubjectInDBBase(**updated_subject_doc)
    return None # Should not happen if update was successful and ID is correct

async def delete_subject_for_user(
    db: AsyncIOMotorDatabase, 
    subject_id_str: str, 
    user_id: PyObjectId
) -> bool:
    """
    Deletes a subject for a user.
    Also updates books in this subject to be uncategorized (sets their subject_id to null).
    """
    subject_to_delete = await get_subject_by_id_for_user(db, subject_id_str, user_id)
    if not subject_to_delete:
        return False # Subject not found or doesn't belong to user

    # Set subject_id to null for all books of this user that were in this subject
    await db[BOOKS_COLLECTION].update_many(
        {"user_id": user_id, "subject_id": subject_to_delete.id},
        {"$set": {"subject_id": None}} 
        # Or {"$unset": {"subject_id": ""}} if you prefer to remove the field
    )

    delete_result = await db[SUBJECTS_COLLECTION].delete_one(
        {"_id": subject_to_delete.id, "user_id": user_id}
    )
    
    return delete_result.deleted_count > 0
