from pydantic import BaseModel, Field
from typing import List, Optional, Literal 
from datetime import datetime
from bson import ObjectId

# Import PyObjectId from user_schemas
from .user_schemas import PyObjectId

class TextForSummarization(BaseModel):
    text_to_summarize: str = Field(..., min_length=10, description="Text selected by the user to be summarized.")

class SummarizationResponse(BaseModel):
    summary: str

class TextForFlashcards(BaseModel):
    text_to_generate_from: str = Field(..., min_length=10, description="Text selected by the user to generate flashcards from.")
    book_id: Optional[str] = Field(None, description="Optional: ID of the book these flashcards are from")
    topic_id: Optional[str] = Field(None, description="Optional: ID of the topic these flashcards are for")
    topic_name: Optional[str] = Field(None, description="Optional: Name of the topic for labeling")

class Flashcard(BaseModel):
    front: str = Field(..., description="The front content of the flashcard (e.g., question or term).")
    back: str = Field(..., description="The back content of the flashcard (e.g., answer or definition).")

class FlashcardsResponse(BaseModel):
    flashcards: List[Flashcard] = Field(..., description="A list of generated flashcards.")

class TextForStudyNotes(BaseModel):
    text_to_generate_notes_from: str = Field(..., min_length=20, description="Text selected by the user to generate study notes from.")

class StudyNotesResponse(BaseModel):
    study_notes: str = Field(..., description="The generated structured study notes.")

class TextForQuestionAnswer(BaseModel):
    text_to_generate_from: str = Field(..., min_length=20, description="Text selected by the user to generate questions and answers from.")

class QuestionAnswerPair(BaseModel):
    question: str = Field(..., description="A generated question from the text.")
    answer: str = Field(..., description="The corresponding answer to the generated question.")

class QuestionAnswerResponse(BaseModel):
    qna_pairs: List[QuestionAnswerPair] = Field(..., description="A list of generated question and answer pairs.")

# --- (MODIFIED) This class is now updated ---
class QuizGenerationRequest(BaseModel):
    topic_id: Optional[str] = Field(None, description="The ID of the BookTopic to generate the quiz from.")
    book_id: Optional[str] = Field(None, description="The ID of the Book - will use random topic if topic_id not provided.")
    num_questions: int = Field(10, ge=1, le=20, description="Number of questions to generate. Defaults to 10 as per plan.")
# --- End of modification ---

class QuizQuestion(BaseModel):
    question_text: str = Field(..., description="The question generated by the AI.")
    correct_answer: str = Field(..., description="The precise, short AI-generated correct answer.")
    answer_variants: List[str] = Field(..., description="A list of acceptable, alternative answers.") # <-- ADD THIS
    explanation: str = Field(..., description="A brief explanation for the correct answer.")

class GeneratedQuiz(BaseModel):
    quiz_id: str = Field(..., description="A temporary ID for tracking the quiz session (e.g., a hash or UUID).")
    book_id: str = Field(..., description="The ID of the book this quiz belongs to.")
    topic_name: str = Field(..., description="The name/subject of the quiz topic.")
    questions: List[QuizQuestion] = Field(..., description="The list of questions and their correct answers.")

class UserAnswer(BaseModel):
    question_text: str = Field(..., description="The original question text (for verification).")
    user_answer: str = Field(..., description="The user's short answer attempt.")

class QuizEvaluationRequest(BaseModel):
    quiz_id: str = Field(..., description="The temporary ID of the quiz being evaluated.")
    attempted_answers: List[UserAnswer]
    book_id: str = Field(..., description="The ID of the book this quiz belongs to.")
    topic_name: str = Field(..., description="The name or identifier of the topic the quiz was for.")

class EvaluatedQuestionResult(BaseModel):
    question_text: str
    user_answer: str
    correct_answer: str
    correct_explanation: str 
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity between user answer and correct answer.")

class QuizEvaluationResponse(BaseModel):
    quiz_id: str
    total_score: float = Field(..., ge=0.0, le=1.0, description="The average similarity score across all questions (0.0 to 1.0).")
    total_grade: str = Field(..., description="A letter grade or qualitative description based on total_score.")
    results: List[EvaluatedQuestionResult]
    book_id: str | None = Field(None, description="The ID of the book this quiz belongs to, for progress tracking.")
    
    # AI Mentor Recommendations
    study_recommendations: Optional[str] = Field(None, description="Personalized study plan from AI mentor.")
    weak_topics: Optional[List[str]] = Field(None, description="Topics the student struggled with.")
    strong_topics: Optional[List[str]] = Field(None, description="Topics the student knows well.")
    next_steps: Optional[List[str]] = Field(None, description="Actionable next steps for improvement.")

# =========================================================================
# --- NEW SCHEMAS FOR AI MENTOR CHAT (Module 8) ---
# =========================================================================

class ChatRequest(BaseModel):
    """Schema for a user's chat query."""
    query: str = Field(..., min_length=1, description="The user's question for the AI Mentor.")

class ChatResponse(BaseModel):
    """Schema for the AI Mentor's response."""
    answer: str = Field(..., description="The AI-generated answer based on the book's content.")
    sources: List[str] = Field(..., description="A list of source text chunks used to generate the answer.")

# =========================================================================
# --- AI MENTOR CHAT HISTORY SCHEMAS (for future sentiment analysis) ---
# =========================================================================

class AIMentorMessageInDB(BaseModel):
    """Schema for storing AI Mentor chat messages in MongoDB."""
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    conversation_id: PyObjectId = Field(..., description="The conversation this message belongs to")
    user_id: PyObjectId = Field(..., description="The user who is chatting with the AI")
    book_id: PyObjectId = Field(..., description="The book being discussed")
    sender_type: Literal["user", "ai"] = Field(..., description="Whether this message is from user or AI")
    content: str = Field(..., description="The message content")
    sources: Optional[List[str]] = Field(None, description="Source chunks used by AI (only for AI messages)")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Placeholder fields for future sentiment analysis
    user_emotion: Optional[str] = Field(None, description="Detected emotion (will be populated by DistilBERT model)")
    sentiment_score: Optional[float] = Field(None, description="Sentiment score from DistilBERT model")
    
    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str, PyObjectId: str, datetime: lambda dt: dt.isoformat()}

class AIMentorConversationInDB(BaseModel):
    """Schema for storing AI Mentor conversations in MongoDB."""
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    user_id: PyObjectId = Field(..., description="The user having this conversation")
    book_id: PyObjectId = Field(..., description="The book being discussed")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    last_activity: datetime = Field(default_factory=datetime.utcnow)
    message_count: int = Field(0, description="Total number of messages in this conversation")
    
    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str, PyObjectId: str, datetime: lambda dt: dt.isoformat()}

class AIMentorMessagePublic(BaseModel):
    """Public-facing schema for AI Mentor messages."""
    id: str
    conversation_id: str
    sender_type: Literal["user", "ai"]
    content: str
    sources: Optional[List[str]] = None
    created_at: datetime
    user_emotion: Optional[str] = None
    sentiment_score: Optional[float] = None
    
    class Config:
        from_attributes = True
        arbitrary_types_allowed = True
        json_encoders = {datetime: lambda dt: dt.isoformat()}

class AIMentorConversationPublic(BaseModel):
    """Public-facing schema for AI Mentor conversations."""
    id: str
    book_id: str
    book_title: Optional[str] = None
    created_at: datetime
    last_activity: datetime
    message_count: int
    last_message_preview: Optional[str] = None
    
    class Config:
        from_attributes = True
        arbitrary_types_allowed = True
        json_encoders = {datetime: lambda dt: dt.isoformat()}

# =========================================================================
# --- NEW SCHEMAS FOR AI STUDY RECOMMENDATIONS (Module 7) ---
# =========================================================================

RecommendationPriority = Literal["High", "Medium"]

# This defines the "toolbox" of all your app features
RecommendedAction = Literal[
    "AI_MENTOR", 
    "TAKE_QUIZ", 
    "VIEW_SUMMARY", 
    "STUDY_FLASHCARDS", 
    "REVIEW_NOTES", 
    "VIEW_QA_PAIRS"
]

class AIStudyRecommendation(BaseModel):
    """
    A single structured recommendation from the LLM.
    """
    priority: RecommendationPriority
    topic_name: str
    score: float = Field(..., description="The average score (0-100)")
    action: RecommendedAction = Field(..., description="The app feature to use")
    recommendation_text: str = Field(..., description="The human-readable text for the user")

class AIRecommendationResponse(BaseModel):
    """
    The full response from the recommendation endpoint, including
    praise for the user's strong topics.
    """
    recommendations: List[AIStudyRecommendation]
    strength_message: Optional[str] = Field(None, description="An encouraging message about the user's strongest topic")



# =========================================================================
# --- NEW SCHEMAS FOR AI GLOBAL RECOMMENDATIONS (Dashboard) ---
# =========================================================================

GlobalRecommendationAction = Literal[
    "REVIEW_WEAKEST_SUBJECT",
    "PRACTICE_NEW_SUBJECT",
    "VIEW_GLOBAL_PROGRESS",
    "TAKE_ANY_QUIZ"
]

class AIGlobalStudyRecommendation(BaseModel):
    """
    A single high-level recommendation for the global dashboard.
    """
    priority: RecommendationPriority # Re-use this from book recommendations
    action: GlobalRecommendationAction
    title: str = Field(..., description="A short, bold title for the recommendation")
    recommendation_text: str = Field(..., description="The human-readable text for the user")

class AIGlobalRecommendationResponse(BaseModel):
    """
    The full response for the global recommendation endpoint.
    """
    recommendations: List[AIGlobalStudyRecommendation]


# =========================================================================
# --- DATABASE SCHEMAS FOR FLASHCARDS & QUIZ SESSIONS ---
# =========================================================================

class FlashcardInDB(BaseModel):
    """Single flashcard stored in MongoDB."""
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    user_id: PyObjectId = Field(..., description="User who created this flashcard set")
    book_id: PyObjectId = Field(..., description="Book this flashcard belongs to")
    topic_id: Optional[PyObjectId] = Field(None, description="Topic ID if created from a specific topic")
    front: str = Field(..., description="Front of the flashcard")
    back: str = Field(..., description="Back of the flashcard")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str, PyObjectId: str, datetime: lambda dt: dt.isoformat()}


class FlashcardSetInDB(BaseModel):
    """Group of flashcards (one set per generation)."""
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    user_id: PyObjectId = Field(..., description="User who created this flashcard set")
    book_id: PyObjectId = Field(..., description="Book this flashcard set belongs to")
    topic_id: Optional[PyObjectId] = Field(None, description="Topic ID if created from a specific topic")
    topic_name: Optional[str] = Field(None, description="Name of the topic")
    flashcard_count: int = Field(..., description="Number of flashcards in this set")
    source_text: str = Field(..., description="The original text these flashcards were generated from")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str, PyObjectId: str, datetime: lambda dt: dt.isoformat()}


class FlashcardPublic(BaseModel):
    """Public-facing flashcard schema for API responses."""
    id: str
    front: str
    back: str
    created_at: datetime
    
    class Config:
        from_attributes = True
        json_encoders = {datetime: lambda dt: dt.isoformat()}


class FlashcardSetPublic(BaseModel):
    """Public-facing flashcard set schema."""
    id: str
    topic_name: Optional[str]
    flashcard_count: int
    created_at: datetime
    flashcards: List[FlashcardPublic] = Field([], description="Flashcards in this set")
    
    class Config:
        from_attributes = True
        json_encoders = {datetime: lambda dt: dt.isoformat()}